language: cpp

compiler:
    - clang
    - gcc

script:
    - mkdir build && cd build && cmake ..  -DCMAKE_BUILD_TYPE=release && make

after_success:
    - ./bam-parser ../test/example.bam
    - ./bam-parser ../test/example.bam 1
    - ./vcf-parser ../test/example.vcf
    - ./vcf-parser-region  ../test/example.vcf 22:167679-175311

os:
    - linux
    - osx

notifications:
    email:
        on_failure: always
        on_success: change
